TYPE_FOOD = 'food'
TYPE_EMPTY = 'empty'
TYPE_VEHICLE = 'vehicle'
TYPE_OBSTACLE = 'obstacle'


EMPTY_COLOR = '#E4E4D4'
FOOD_COLOR = '#FF7878'
VEHICLE_COLOR = '#7FEB0A'
OBSTACLE_COLOR = '#253225'
VISITED_COLOR = '#ff0044'
EXPANDED_COLOR = '#cf1952'
SOLUTION_COLOR = '#0fa0fa'
